%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Professional\Downloads\Визуализация данных в Матлаб\summarized work\TRAIN_RAD_H_ANNO\2019_05_29_MLMS006.txt
%
% Auto-generated by MATLAB on 13-Dec-2021 02:47:38

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["ID", "Coord1", "Coord2", "Type"];
opts.VariableTypes = ["categorical", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Type", "EmptyFieldRule", "auto");

% Import the data
MLMS006 = readtable(".\TRAIN_RAD_H_ANNO\2019_05_29_MLMS006.txt", opts);


%% Clear temporary variables
clear opts